on:
  push:
    branches:
      - main

#    branches-ignore:
#      - main
#      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

#      - name: Setup Maven
#        uses: stCarolos/setup-maven@4.4
#        with:
#          maven-version: 3.8.2

      - name: build action
        run: mvn clean install