on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Maven
        uses: stCarolos/setup-maven@4.4
        with:
          maven-version: 3.8.2

      - name: build action
        run: mvn clean install